--------------------------------------------------------
--  파일이 생성됨 - 수요일-12월-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIE_INFO
--------------------------------------------------------

  CREATE TABLE "JAVA"."MOVIE_INFO" 
   (	"MOVIE_NO" NUMBER(*,0) DEFAULT 1, 
	"MOVIE_TITLE" VARCHAR2(50 BYTE), 
	"MOVIE_POSTER" VARCHAR2(100 BYTE), 
	"MOVIE_TRAILER" VARCHAR2(100 BYTE), 
	"MOVIE_CONTENT" VARCHAR2(1000 BYTE), 
	"MOVIE_TIMES" NUMBER(*,0), 
	"MOVIE_RATING" FLOAT(126), 
	"MOVIE_GENRE" VARCHAR2(80 BYTE), 
	"MOVIE_DIRECTOR" VARCHAR2(30 BYTE), 
	"MOVIE_ACTORS" VARCHAR2(80 BYTE), 
	"MOVIE_GRADE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_NO" IS '번호';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_TITLE" IS '제목';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_POSTER" IS '포스터(이미지 경로)';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_TRAILER" IS '예고편(유튜브 경로)';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_CONTENT" IS '줄거리';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_TIMES" IS '상영시간';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_RATING" IS '평가점수';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_GENRE" IS '장르';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_DIRECTOR" IS '감독';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_ACTORS" IS '주연/조연';
   COMMENT ON COLUMN "JAVA"."MOVIE_INFO"."MOVIE_GRADE" IS '상영등급';
--------------------------------------------------------
--  DDL for Index MOVIE_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."MOVIE_INFO_PK" ON "JAVA"."MOVIE_INFO" ("MOVIE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MOVIE_INFO
--------------------------------------------------------

  ALTER TABLE "JAVA"."MOVIE_INFO" ADD CONSTRAINT "MOVIE_INFO_PK" PRIMARY KEY ("MOVIE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_GRADE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_ACTORS" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_GENRE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_RATING" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_TIMES" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_TRAILER" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_POSTER" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MOVIE_INFO" MODIFY ("MOVIE_NO" NOT NULL ENABLE);
  
-- 샘플 데이터
-- CREATE SEQUENCE mov_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 50000; -- 자동 증가 시퀀스
-- set define off; 대체 변수창 문제 끄기(&)
-- INSERT INTO "JAVA"."MOVIE_INFO" (MOVIE_NO, MOVIE_TITLE, MOVIE_POSTER, MOVIE_TRAILER, MOVIE_CONTENT, MOVIE_TIMES, MOVIE_RATING, MOVIE_GENRE, MOVIE_DIRECTOR, MOVIE_ACTORS, MOVIE_GRADE) VALUES (tmp_seq.NEXTVAL, '겨울왕국2', 'https://movie-phinf.pstatic.net/20191121_221/1574298335357mqgLk_JPEG/movie_image.jpg', 'https://www.youtube.com/watch?v=eSEs4B4H-EA&t=1s', '내 마법의 힘은 어디서 왔을까?
-- 나를 부르는 저 목소리는 누구지?
-- 어느 날 부턴가 의문의 목소리가 엘사를 부르고, 평화로운 아렌델 왕국을 위협한다.
-- 트롤은 모든 것은 과거에서 시작되었음을 알려주며 엘사의 힘의 비밀과 진실을 찾아 떠나야한다고 조언한다.
-- 위험에 빠진 아렌델 왕국을 구해야만 하는 엘사와 안나는 숨겨진 과거의 진실을 찾아
-- 크리스토프, 올라프 그리고 스벤과 함께 위험천만한 놀라운 모험을 떠나게 된다.
-- 자신의 힘을 두려워했던 엘사는 이제 이 모험을 헤쳐나가기에 자신의 힘이 충분하다고 믿어야만 하는데…
-- 두려움을 깨고 새로운 운명을 만나다!', '103', '8.93', '애니메이션, 모험, 코미디, 가족, 판타지, 뮤지컬', '크리스 벅, 제니퍼 리', '크리스틴 벨(안나 목소리), 이디나 멘젤(엘사 목소리)', '1');